// templates/vue-p5-component.vue
<template>
  <div ref="canvasContainer" class="p5-container" :style="containerStyle"></div>
</template>

<script>
/**
 * Vue 3 + p5.js Component Template
 *
 * Installation:
 *   npm install p5
 *
 * Usage:
 *   <P5Background
 *     :particleCount="100"
 *     :backgroundColor="'#1a1a2e'"
 *     :fullscreen="true"
 *   />
 */

import { ref, onMounted, onUnmounted, computed, watch } from 'vue';

export default {
  name: 'P5Background',

  props: {
    particleCount: {
      type: Number,
      default: 100
    },
    backgroundColor: {
      type: String,
      default: '#1a1a2e'
    },
    particleColor: {
      type: Array,
      default: () => [100, 200, 255]
    },
    connectionDistance: {
      type: Number,
      default: 100
    },
    fullscreen: {
      type: Boolean,
      default: true
    },
    width: {
      type: Number,
      default: 800
    },
    height: {
      type: Number,
      default: 600
    }
  },

  setup(props) {
    const canvasContainer = ref(null);
    let p5Instance = null;
    let particles = [];

    const containerStyle = computed(() => {
      if (props.fullscreen) {
        return {
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100vw',
          height: '100vh',
          zIndex: -1
        };
      }
      return {
        width: `${props.width}px`,
        height: `${props.height}px`
      };
    });

    const sketch = (p5) => {
      class Particle {
        constructor() {
          this.pos = p5.createVector(p5.random(p5.width), p5.random(p5.height));
          this.vel = p5.createVector(p5.random(-0.5, 0.5), p5.random(-0.5, 0.5));
          this.size = p5.random(2, 4);
          this.alpha = p5.random(100, 200);
        }

        update() {
          this.pos.add(this.vel);

          // Wrap around edges
          if (this.pos.x < 0) this.pos.x = p5.width;
          if (this.pos.x > p5.width) this.pos.x = 0;
          if (this.pos.y < 0) this.pos.y = p5.height;
          if (this.pos.y > p5.height) this.pos.y = 0;
        }

        display() {
          p5.noStroke();
          p5.fill(
            props.particleColor[0],
            props.particleColor[1],
            props.particleColor[2],
            this.alpha
          );
          p5.ellipse(this.pos.x, this.pos.y, this.size);
        }

        connectNearby(others) {
          for (const other of others) {
            const d = p5.dist(this.pos.x, this.pos.y, other.pos.x, other.pos.y);
            if (d < props.connectionDistance && d > 0) {
              const alpha = p5.map(d, 0, props.connectionDistance, 100, 0);
              p5.stroke(
                props.particleColor[0],
                props.particleColor[1],
                props.particleColor[2],
                alpha
              );
              p5.strokeWeight(0.5);
              p5.line(this.pos.x, this.pos.y, other.pos.x, other.pos.y);
            }
          }
        }
      }

      p5.setup = () => {
        const canvas = p5.createCanvas(
          props.fullscreen ? p5.windowWidth : props.width,
          props.fullscreen ? p5.windowHeight : props.height
        );
        canvas.parent(canvasContainer.value);

        // Initialize particles
        particles = [];
        for (let i = 0; i < props.particleCount; i++) {
          particles.push(new Particle());
        }
      };

      p5.draw = () => {
        p5.background(props.backgroundColor);

        for (const particle of particles) {
          particle.update();
          particle.display();
          particle.connectNearby(particles);
        }
      };

      p5.windowResized = () => {
        if (props.fullscreen) {
          p5.resizeCanvas(p5.windowWidth, p5.windowHeight);
        }
      };
    };

    onMounted(async () => {
      // Dynamic import for SSR compatibility
      const p5Module = await import('p5');
      const P5 = p5Module.default;
      p5Instance = new P5(sketch);
    });

    onUnmounted(() => {
      if (p5Instance) {
        p5Instance.remove();
      }
    });

    // Watch for prop changes
    watch(() => props.particleCount, (newCount) => {
      if (p5Instance) {
        // Reinitialize particles
        const diff = newCount - particles.length;
        if (diff > 0) {
          for (let i = 0; i < diff; i++) {
            particles.push(new particles[0].constructor());
          }
        } else if (diff < 0) {
          particles.splice(newCount);
        }
      }
    });

    return {
      canvasContainer,
      containerStyle
    };
  }
};
</script>

<style scoped>
.p5-container {
  overflow: hidden;
}

.p5-container canvas {
  display: block;
}
</style>

<!--
USAGE EXAMPLE:

<template>
  <div>
    <P5Background
      :particleCount="150"
      backgroundColor="#0d1117"
      :particleColor="[100, 200, 255]"
      :connectionDistance="120"
      :fullscreen="true"
    />

    <main class="content">
      <h1>Your Content Here</h1>
    </main>
  </div>
</template>

<script>
import P5Background from './vue-p5-component.vue';

export default {
  components: { P5Background }
};
</script>

<style>
.content {
  position: relative;
  z-index: 1;
  color: white;
}
</style>
-->

// templates/react-p5-component.tsx
/**
 * React + p5.js Component Template
 *
 * Installation:
 *   npm install react-p5
 *   # or
 *   npm install @p5-wrapper/react
 *
 * Usage:
 *   <ParticleBackground />
 */

import React from 'react';
import Sketch from 'react-p5';
import type p5Types from 'p5';

interface Particle {
  pos: p5Types.Vector;
  vel: p5Types.Vector;
  size: number;
  alpha: number;
}

interface ParticleBackgroundProps {
  particleCount?: number;
  backgroundColor?: string;
  particleColor?: [number, number, number];
  connectionDistance?: number;
}

const ParticleBackground: React.FC<ParticleBackgroundProps> = ({
  particleCount = 100,
  backgroundColor = '#1a1a2e',
  particleColor = [100, 200, 255],
  connectionDistance = 100
}) => {
  let particles: Particle[] = [];

  const setup = (p5: p5Types, canvasParentRef: Element) => {
    p5.createCanvas(p5.windowWidth, p5.windowHeight).parent(canvasParentRef);

    // Initialize particles
    for (let i = 0; i < particleCount; i++) {
      particles.push({
        pos: p5.createVector(p5.random(p5.width), p5.random(p5.height)),
        vel: p5.createVector(p5.random(-0.5, 0.5), p5.random(-0.5, 0.5)),
        size: p5.random(2, 4),
        alpha: p5.random(100, 200)
      });
    }
  };

  const draw = (p5: p5Types) => {
    p5.background(backgroundColor);

    // Update and display particles
    for (const particle of particles) {
      // Update position
      particle.pos.add(particle.vel);

      // Wrap around edges
      if (particle.pos.x < 0) particle.pos.x = p5.width;
      if (particle.pos.x > p5.width) particle.pos.x = 0;
      if (particle.pos.y < 0) particle.pos.y = p5.height;
      if (particle.pos.y > p5.height) particle.pos.y = 0;

      // Display particle
      p5.noStroke();
      p5.fill(particleColor[0], particleColor[1], particleColor[2], particle.alpha);
      p5.ellipse(particle.pos.x, particle.pos.y, particle.size);

      // Connect to nearby particles
      for (const other of particles) {
        const d = p5.dist(particle.pos.x, particle.pos.y, other.pos.x, other.pos.y);
        if (d < connectionDistance && d > 0) {
          const alpha = p5.map(d, 0, connectionDistance, 100, 0);
          p5.stroke(particleColor[0], particleColor[1], particleColor[2], alpha);
          p5.strokeWeight(0.5);
          p5.line(particle.pos.x, particle.pos.y, other.pos.x, other.pos.y);
        }
      }
    }
  };

  const windowResized = (p5: p5Types) => {
    p5.resizeCanvas(p5.windowWidth, p5.windowHeight);
  };

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, zIndex: -1 }}>
      <Sketch setup={setup} draw={draw} windowResized={windowResized} />
    </div>
  );
};

export default ParticleBackground;

// ============================================
// Alternative: Using @p5-wrapper/react (newer)
// ============================================

/*
import { ReactP5Wrapper } from '@p5-wrapper/react';
import type { P5CanvasInstance, SketchProps } from '@p5-wrapper/react';

interface MySketchProps extends SketchProps {
  particleCount: number;
}

function sketch(p5: P5CanvasInstance<MySketchProps>) {
  let particles: Particle[] = [];
  let particleCount = 100;

  p5.setup = () => {
    p5.createCanvas(p5.windowWidth, p5.windowHeight);
    initParticles();
  };

  p5.updateWithProps = (props: MySketchProps) => {
    if (props.particleCount !== particleCount) {
      particleCount = props.particleCount;
      initParticles();
    }
  };

  function initParticles() {
    particles = [];
    for (let i = 0; i < particleCount; i++) {
      particles.push({
        pos: p5.createVector(p5.random(p5.width), p5.random(p5.height)),
        vel: p5.createVector(p5.random(-0.5, 0.5), p5.random(-0.5, 0.5)),
        size: p5.random(2, 4),
        alpha: p5.random(100, 200)
      });
    }
  }

  p5.draw = () => {
    // ... drawing logic
  };

  p5.windowResized = () => {
    p5.resizeCanvas(p5.windowWidth, p5.windowHeight);
  };
}

export const P5Background: React.FC<{ particleCount?: number }> = ({
  particleCount = 100
}) => {
  return <ReactP5Wrapper sketch={sketch} particleCount={particleCount} />;
};
*/
